### ISSUE TITLE
[BUG] Steamdeck Retroarch won't Download

### ISSUE THREAD

**Issue by al12gamer** [icculus/twisty-little-utilities#1]
Greetings! I'm on my Steam Deck running the latest Stable OS release of SteamOS 3.4. I have Retroarch installed via steam. When I run the `steamdeck-retroarch-download-all-cores.sh` script from Konsole, I get the following result:
`RetroArch/steam doesn't appear to be installed. Giving up.`

Is this because the script looks in a different path than where the software is installed? Upon further inspection, the bash script looks in `$HOME/.local/share/Steam/steamapps/common/RetroArch` and the currently-installed-on-NVMe RetroArch install seems to be in `/home/deck/.local/share/Steam/steamapps/common/RetroArch` ...so I'm at a bit of a loss here, any ideas?

**Comment by icculus** [comment]
Hmm, that should be right ("$HOME" should become "/home/deck" when the script runs). Are you sure the RetroArch installation isn't damaged or missing?

**Comment by al12gamer** [comment]
file:///home/deck/Pictures/Screenshot_20230111_143924.png
I went ahead and validated all the files for my Retroarch install. 
Looks like I'm still getting `RetroArch/steam doesn't appear to be installed. Giving up.`
Here's what a neofetch from Konsole looks like:
```
(deck@gabegear ~)$ neofetch
              .,,,,.                  deck@gabegear 
        .,'onNMMMMMNNnn',.            ------------- 
     .'oNMANKMMMMMMMMMMMNNn'.         OS: SteamOS Holo x86_64 
   .'ANMMMMMMMXKNNWWWPFFWNNMNn.       Host: Jupiter 1 
  ;NNMMMMMMMMMMNWW'' ,.., 'WMMM,      Kernel: 5.13.0-valve36-1-neptune 
 ;NMMMMV+##+VNWWW' .+;'':+, 'WMW,     Uptime: 4 mins 
,VNNWP+######+WW,  +:    :+, +MMM,    Packages: 932 (pacman), 36 (flatpak) 
'+#############,   +.    ,+' +NMMM    Shell: bash 5.1.16 
  '*#########*'     '*,,*' .+NMMMM.   Resolution: 2560x1440 
     `'*###*'          ,.,;###+WNM,   DE: Plasma 5.26.1 
         .,;;,      .;##########+W    WM: KWin 
,',.         ';  ,+##############'    Theme: Vapor [Plasma], Breeze [GTK2/3] 
 '###+. :,. .,; ,###############'     Icons: [Plasma], breeze-dark [GTK2/3] 
  '####.. `'' .,###############'      Terminal: konsole 
    '#####+++################'        CPU: AMD Custom APU 0405 (8) @ 2.800GHz 
      '*##################*'          GPU: AMD ATI AMD Custom GPU 0405 
         ''*##########*''             Memory: 3041MiB / 14818MiB 
              ''''''
                                                              
                                                              

```

**Comment by icculus** [comment]
haha, "gabegear"

At the top of the script is this line:

```bash
#set -x
```

Take the `#` off that, and see what it prints out when you run it.

**Comment by al12gamer** [comment]
Sorry for the slow comments, been working on reviving some other hardware today. Here's the output when uncommenting that line:
```
(deck@gabegear twisty-little-utilities)$ ./steamdeck-retroarch-download-all-cores.sh 
++ basename ./steamdeck-retroarch-download-all-cores.sh
+ ME=steamdeck-retroarch-download-all-cores.sh
+ RETROPATH=/home/deck/.local/share/Steam/steamapps/common/RetroArch
+ RETROCOREPATH=/home/deck/.local/share/Steam/steamapps/common/RetroArch/cores
+ RETROBIN=/home/deck/.local/share/Steam/steamapps/common/RetroArch/retroarch
+ '[' '!' -f /home/deck/.local/share/Steam/steamapps/common/RetroArch/retroarch ']'
++ strings /home/deck/.local/share/Steam/steamapps/common/RetroArch/retroarch
++ grep '\[INFO\] Version:'
++ awk '{ print $3 }'
+ RETROVER=1.14.0
+ '[' x1.14.0 = x ']'
+ RETROTMPDIR=/home/deck/steamdeck_retroarch_core_update_tmp
+ LASTCHECKPATH=/home/deck/.last_steamdeck_retroarch_core_update.txt
++ cat /home/deck/.last_steamdeck_retroarch_core_update.txt
+ LASTCHECKVER=1.14.0
+ '[' x1.14.0 = x1.14.0 ']'
+ exit 0
```

**Comment by al12gamer** [comment]
If the version of the cores matches latest, does the thing result in just saying that retroarch isn't found?

**Comment by icculus** [comment]
It definitely found it that time, and figured out that it's version 1.14.0; maybe something changed that fixed the problem? Go ahead and add the `#` back in and see if it still works?

**Comment by al12gamer** [comment]
Made this little recording this time around. Added the comment back in and it still says retroarch/steam isn't installed hahaha.
https://asciinema.org/a/551101

**Comment by icculus** [comment]
Ah, okay.

No output is good: that means there was nothing to do; it only says something when there's an update to be made; this is so it can run in a cronjob without emailing you every time it runs, and only alert you if there was a problem or an update was made.

As for the failure: it's failing when you run it under "sudo" because the root user's home directory _doesn't_ have RetroArch installed (and shouldn't, either). There shouldn't be a reason to run this script under sudo, as it doesn't need admin access to get things done.

So...I think you're okay here?

**Comment by al12gamer** [comment]
Yup, thank you for further clarification!
